### ISSUE TITLE
Exclude options in mypy.ini aren't understood by mypyls due to pinned version

### ISSUE THREAD

**Issue by harshita-gupta** [matangover/mypyls#11]
I'm guessing that's because this ext is pinned to mypy .800, and exclude is a .812 option. Is there a reason that the mypy version on this ext is pinned?

**Comment by harshita-gupta** [comment]
Ah, solved my own issue by looking @ #3. 

> Btw you don't need to clone the repo to update mypy – simply update mypy in the mypyls virtualenv (~/.mypyls/bin/pip install -U mypy if you used the default path).

This did the trick for me!

**Comment by matangover** [comment]
Thanks :) I'm happy this fixed it for you. By the way, would you be willing to beta test a new version of the extension? I modified it so that it works with mypy's built in daemon instead of the custom `mypyls`. This way pinning it to a specific version will no longer be needed. But I would like for someone apart from me to test it before I release it, because it's a major change.

**Comment by harshita-gupta** [comment]
Yes, would be happy to!

**Comment by matangover** [comment]
Thank you! I'll send it in the next few days.

**Comment by matangover** [comment]
Hi @harshita-gupta here is the [beta version](https://github.com/matangover/mypy-vscode/issues/27), I'll be happy if you could test it on your machine
